version: '3.9'
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    # privileged: true
    restart: always
    # ports:
    #   - '8000:8000'
    #   - '9443:9443'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - 'portainer_data:/data'
    networks:
      - www

volumes:
  portainer_data:

networks:
  www:
    name: www
